### PR TITLE
Added Romanian language.

### PR DESCRIPTION
**Pull request by mdomnita**
Added Romanian language and Romanian translation file.

### CODE REVIEW

**Comment by 1ec5** [comment]
Thanks @mdomnita! We manage the translations at [Transifex](https://www.transifex.com/project-osrm/osrm-text-instructions/). I’ve added Romanian there, added you as a translator, and imported your ro.json into the project. Please follow [these instructions](https://github.com/Project-OSRM/osrm-text-instructions#translations) to complete the localization, including updating test fixtures. Thanks again!

**Comment by mdomnita** [comment]
dear Minh,

thank you very much. I am out on holiday at the moment and only have mobile but I will look into it in about two weeks.

Have a nice day,
Matei

Sent from my Fire

On 6 May 2017, at 22:09, Minh Nguyễn <notifications@github.com> wrote:

Thanks @mdomnita! We manage the translations at Transifex. I’ve added Romanian there, added you as a translator, and imported your ro.json into the project. Please follow these instructions to complete the localization, including updating test fixtures. Thanks again!

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.￼

{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Project-OSRM/osrm-text-instructions","title":"Project-OSRM/osrm-text-instructions","subtitle":"GitHub repository","main_image_url":"<a href="https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png">https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png</a>","avatar_image_url":"<a href="https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png">https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png</a>","action":{"name":"Open in GitHub","url":"<a href="https://github.com/Project-OSRM/osrm-text-instructions">https://github.com/Project-OSRM/osrm-text-instructions</a>"}},"updates":{"snippets":[{"icon":"PERSON","message":"@1ec5 in #105: Thanks @mdomnita! We manage the translations at [Transifex](<a href="https://www.transifex.com/project-osrm/osrm-text-instructions">https://www.transifex.com/project-osrm/osrm-text-instructions</a>/). I’ve added Romanian there, added you as a translator, and imported your ro.json into the project. Please follow [these instructions](<a href="https://github.com/Project-OSRM/osrm-text-instructions#translations">https://github.com/Project-OSRM/osrm-text-instructions#translations</a>) to complete the localization, including updating test fixtures. Thanks again!"}],"action":{"name":"View Pull Request","url":"<a href="https://github.com/Project-OSRM/osrm-text-instructions/pull/105#issuecomment-299660001">https://github.com/Project-OSRM/osrm-text-instructions/pull/105#issuecomment-299660001</a>"}}}

**Comment by daniel-j-h** [comment]
👋 any update here?

**Comment by mdomnita** [comment]
I finished translating everything on transifex but I don't know what I should do next. When I did the pull request I just added the file and everything was okay but I was not familiar with the system.

**Comment by 1ec5** [comment]
The following steps need to take place before we can add Romanian support:

1. Translate more strings at Transifex. It looks like some of the files in this PR were translated by hand. That’s unfortunate, because the next time someone runs `npm run transifex`, your translations will be overridden with English strings automatically.
1. Run `npm run transifex` and `git checkout` the files for other languages.
1. Run `UPDATE=1 npm test` and check in the results.

I’d do some of these steps for you, but it looks like you have the “Allow edits from maintainers” option disabled.

**Comment by mdomnita** [comment]
Hello @1ec5 . I went to transifex, translated everything. I got the translation json, I will copy it to the new file.
I have no idea where to set  “Allow edits from maintainers” . When I translated this there was no transifex folder, just the language files that I created a pull request for. I will try to do it mysalf and tell you if I succeed.

**Comment by 1ec5** [comment]
> I set “Allow edits from maintainers” , it's checked here .

Ah, I guess GitHub is preventing me from making edits because I’m technically not a maintainer, just a contributor. 😅

I’m not sure what’s causing transifex.js to crash; it’s entirely possible that something in there assumes POSIX paths, since none of this project’s main developers uses Windows.

**Comment by 1ec5** [comment]
> I set “Allow edits from maintainers” , it's checked here .

Thanks, your code changes look good, so I’ve rebased your commits atop master (v0.7.0), cleaned up the Windows line endings, and update the test fixtures.

I’m not sure what’s causing transifex.js to crash; it’s entirely possible that something in there assumes POSIX paths, since none of this project’s main developers uses Windows.

**Comment by 1ec5** [comment]
Thanks for your help @mdomnita!

**Pull request merged**
