### PR TITLE
Test phrases

### LINKED ISSUE #143: Test phrases
The phrases added in #141 should be subject to our string generation tests, since they’re all format strings.

/cc @mcwhittemore

### PR DESCRIPTION
**Pull request by 1ec5**
Added a convenience method for tokenizing a phrase, plus tests and test fixtures against that method.

Fixes #143.

/cc @mcwhittemore @lyzidiamond

### CODE REVIEW

**Comment by yuryleb** [comment]
It's not related to this PR directly but is it possible also to change arguments order of new tokenize(instruction, replaceTokens, language) function to move `language` argument first as in all other index.js's methods?

**Comment by 1ec5** [comment]
@yuryleb, thanks for the suggestion. I opened #149 with that change.

**Comment by 1ec5** [comment]
I understand your hesitation around the additional `compilePhrase()` method. I ended up adding it mainly because it was necessary for unit testing phrase generation. I’d be fine with considering it a private method and not documenting it for clients (although it still needs to be exported for the tests).

**Comment by mcwhittemore** [comment]
Can't the tests just call `compile` and then `tokenize`?

**Comment by 1ec5** [comment]
> Can't the tests just call `compile` and then `tokenize`?

Good point. Done.

**Pull request merged**
