### PR TITLE
Adds an instruction worded for upcoming arrival

### PR DESCRIPTION
**Pull request by allierowan**
- [x] Add phrases in translation files
 - [x] Add changelog entry
 - [x] Add tests
 - [ ] Review

### CODE REVIEW

**Comment by 1ec5** [comment]
This fixes #61.

**Comment by 1ec5** [comment]
Technically the Directions API can at any time produce an unexpected `modifier` – hence the `default` cases. In that case, `compile` will wind up with a more deeply nested object than expected:

https://github.com/Project-OSRM/osrm-text-instructions/blob/d91209a433087350a7782bb5bb176c52244ed36b/index.js#L129-L137

We have special cases for `use lane`, `rotary`, and `roundabout` instructions that dig deeper into the object, so that `instruction` ends up being a string rather than an object. We’ll need a similar case for `arrive`. Our tests aren’t catching this case because they only cover the known `modifier`s.

By the way, we’ll eventually need more keys alongside `default` for #110 and #134.

**Comment by 1ec5** [comment]
> Technically the Directions API can at any time produce an unexpected `modifier` – hence the `default` cases. In that case, `compile` will wind up with a more deeply nested object than expected

My bad, I was misreading the PR. It’s odd that additions to the `v5` object don’t result in any changes to index.js, but I take it that’s because these strings are intended to be used in `tokenize` only and not in `compile`, correct?

**Comment by allierowan** [comment]
@1ec5 yeah, that was what I was thinking. I suppose we could expose it to compile by adding some sort of flag?

**Pull request merged**
