### PR TITLE
Spanish

### PR DESCRIPTION
**Pull request by 1ec5**
Added Spanish translation from Transifex.

@josek5494, thank you for your contributions! Please review the test fixtures in this PR for any edge cases that may need to be overridden. Incidentally, it looks like we got very lucky in that we only ended up needing feminine ordinals (for _destina_ and _salida_).

/cc @MallorcaRedes

### CODE REVIEW

**Comment by 1ec5** [comment]
Also, if any strings need to differ from country to country (such as Spain versus Colombia), please let me know and I’ll be happy to add the appropriate languages to the Transifex project.

**Comment by yuryleb** [comment]
Please don't forget to remove Spanish code replacement in frontend's [itinerary_builder.js](https://github.com/Project-OSRM/osrm-frontend/blob/gh-pages/src/itinerary_builder.js#L5) code after all.

**Comment by 1ec5** [comment]
Oh, interesting. @freenerd, what’s the story behind that special case? Do we need to remove special cases anywhere else in the frontend?

**Comment by perliedman** [comment]
@1ec5 my guess is that the frontend relies on existing i18n in Leaflet Routing Machine for languages that are not yet in osrm-text-instructions.

**Comment by yuryleb** [comment]
But my guess is easier - frontend has its own [Spanish translation block](https://github.com/Project-OSRM/osrm-frontend/blob/gh-pages/i18n/es.js) - this automatically enables Spanish 'Change language' option - so to prevent 'Missing language' error from osrm-text-instructions, this lang code is temporary replaced :wink:

**Comment by freenerd** [comment]
@yuryleb and @perliedman are correct. Ticketed in https://github.com/Project-OSRM/osrm-frontend/issues/232

**Pull request merged**
