### PR TITLE
fix #62 pedestrian token

### LINKED ISSUE #62: Instructions containing pedestrian tokens
using the foot profile many names of steps are tokens like: ` {highway:pedestrian}`, `{highway:service}` or `{highway:footway}`

the compiled instructions are containing these tokens:
`Turn right onto {highway:footway}`

### PR DESCRIPTION
**Pull request by ronhippler**

### CODE REVIEW

**Comment by daniel-j-h** [comment]
I'd love to get this properly fixed upstream instead: https://github.com/Project-OSRM/osrm-backend/issues/3231.

**Comment by milovanderlinden** [comment]
I want this too! This will not only work for pedestrian, but also for footway and cycleway

**Comment by freenerd** [comment]
Sorry @ronhippler, I'll close this in favour of the upstream fix @daniel-j-h suggested.

As a quick-fix the code in this PR looks fine though. Thanks for opening.

**Comment by daniel-j-h** [comment]
This landed in https://github.com/Project-OSRM/osrm-backend/pull/3262 and will be in the next 5.5 release.

**Pull request closed without merging**
