### PR TITLE
Add exit rotary/roundabout

### PR DESCRIPTION
**Pull request by bsudekum**
Adds handling for new types `exit rotary` and `exit roundabout`. 

This can be handled as a simple turn, no special instruction needed.

/cc @1ec5 @mcwhittemore

### CODE REVIEW

**Comment by bsudekum** [comment]
Unsure about `throughabouts`. Thoughts @danpat @daniel-j-h?

**Comment by bsudekum** [comment]
@1ec5 will update the changelog when we do a release. More items might go into the next release, unsure if it will be a `0.6.2` or `0.7.0` release.

**Comment by 1ec5** [comment]
> will update the changelog when we do a release.

Normally we maintain a running changelog with “master” or “unreleased” as the section heading.

> What about throughabouts – does OSRM emit an exit instruction for those? If so, would “Go straight” be an appropriate exit instruction?

Apparently throughabouts get no instructions at all: Project-OSRM/osrm-backend#4333.

**Comment by mcwhittemore** [comment]
@bsudekum - this just adds tests right because `default` should work here?

**Comment by bsudekum** [comment]
@mcwhittemore yep. In the future if we'd like to add special handling for rotary/roundabout exits, we can.

**Comment by 1ec5** [comment]
This is failing on master: https://travis-ci.org/Project-OSRM/osrm-text-instructions/builds/274284651.

**Comment by bsudekum** [comment]
@1ec5 I think it may have to do with: https://github.com/Project-OSRM/osrm-text-instructions/pull/148

Logging memo locally while running tests, I'm seeing: 


```
ok 7320 other/motorway_ref_has_number_uturn.json/uk
Quẹo ngược lại {way_name}
Quẹo ngược lại Ref1
Quẹo ngược lại Ref1
Quẹo ngược lại Ref1
Quẹo ngược lại Ref1
Quẹo ngược lại Ref1
Quẹo ngược lại Ref1
Quẹo ngược lại Ref1
Quẹo ngược lại Ref1
ok 7321 other/motorway_ref_has_number_uturn.json/vi
调头上{way_name}
调头上Ref1
调头上Ref1
调头上Ref1
调头上Ref1
调头上Ref1
调头上Ref1
调头上Ref1
调头上Ref1
ok 7322 other/motorway_ref_has_number_uturn.json/zh-Hans
{ name: 'Cool highway', ref: 'Ref1' }
/Users/bobby/Documents/mapbox/osrm-text-instructions/index.js:205
                return memo.replace('{' + token + '}', tokens[token]);
                            ^

TypeError: memo.replace is not a function
    at /Users/bobby/Documents/mapbox/osrm-text-instructions/index.js:205:29
    at Array.reduce (native)
    at Object.tokenize (/Users/bobby/Documents/mapbox/osrm-text-instructions/index.js:203:47)
    at Object.compile (/Users/bobby/Documents/mapbox/osrm-text-instructions/index.js:153:32)
    at Object.keys.forEach (/Users/bobby/Documents/mapbox/osrm-text-instructions/test/index_test.js:194:49)
    at Array.forEach (native)
    at /Users/bobby/Documents/mapbox/osrm-text-instructions/test/index_test.js:192:51
    at Array.forEach (native)
    at /Users/bobby/Documents/mapbox/osrm-text-instructions/test/index_test.js:179:55
    at Array.forEach (native)```

Looking into this.

**Comment by 1ec5** [comment]
Thanks, it looks like #148 collided with #149. PR forthcoming.

**Comment by 1ec5** [comment]
> will update the changelog when we do a release.

This didn’t happen. It can be helpful to add to the changelog as part of the PR, when the changes are top of mind.

/cc @bsudekum @mcwhittemore

**Pull request merged**
